python run_tests.py --model=1 --task=1
python run_tests.py --model=1 --task=2
python run_tests.py --model=1 --task=3
python run_tests.py --model=1 --task=4
python run_tests.py --model=1 --task=5
python run_tests.py --model=2 --task=1
python run_tests.py --model=2 --task=2
python run_tests.py --model=2 --task=3
python run_tests.py --model=2 --task=4
python run_tests.py --model=2 --task=5
python run_tests.py --model=3 --task=1
python run_tests.py --model=3 --task=2
python run_tests.py --model=3 --task=3
python run_tests.py --model=3 --task=4
python run_tests.py --model=3 --task=5
python run_tests.py --model=4 --task=1
python run_tests.py --model=4 --task=2
python run_tests.py --model=4 --task=3
python run_tests.py --model=4 --task=4
python run_tests.py --model=4 --task=5
python run_tests.py --model=5 --task=1
python run_tests.py --model=5 --task=2
python run_tests.py --model=5 --task=3
python run_tests.py --model=5 --task=4
python run_tests.py --model=5 --task=5
